## Anggraeni Bakti Setianingrum

## 200601110075

# Catatan Pertemuan 6

In [ ]:
f = open ('coba.txt','r')
print(f.read())

Nama saya Anggraeni Bakti Setianingrum


# Numpy

Topik utama dari NumPy adalah array multidimensi yang diindeks oleh tuple atau pasangan bilangan bulat positif. Dalam NumPy dimensi disebut sebagai axis, dan banyaknya axis disebut rank. Sebagai contoh, koordinat sebuah titik diruang 3D dinyatakan sebagai [1,2,1] yang merupakan sebuah array dengan rank 1 karena terdiri dari satu axis. Sedangkan panjang axis tersebut adalah 3. 

Pada contoh berikut,array-nya mempunyai rank 2. Axis pertama panjangnya 2, dan axis kedua panjangnya 3.


In [ ]:
[[1., 0., 0.],
 [0., 1., 2.]]

array NumPy disebut sebagai **ndarray**, atau dikenal juga dengan sebutan **array**. Catat bahwa **numpy.array** tidak sama dengan array Standard Python **array.array**, yang hanya bisa digunakan untuk array satu dimensi dan dengan fitur yang lebih sedikit. Atribut yang paling penting dari **ndarray** adalah:

**ndarray.ndim** : banyaknya axis atau dimensi dari array. Di Python, banyaknya dimensi disebut sebagai **rank**.

**ndarray.shape** : dimensi dari array. Ini adalah pasangan bilangan bulat yang menunjukkan ukuran array di setiap dimensi. Untuk matriks dengan **n** baris dan **m** kolom,bentuknya adalah **(n, m)**. Panjang dari pasangan **shape** adalah **rank**, atau jumlah dimensi, **ndim**.

**ndarray.size** : jumlah elemen dari array. Ini sama dengan perkalian elemen dari **shape**.

**ndarray.dtype** : sebuah objek yang menggambarkan jenis elemen dalam array. Seseorang dapat membuat atau menentukan jenis dtype menggunakan jenis Python standar. Selain itu NumPy menyediakan jenisnya sendiri. **numpy.int32,numpy.int16**, dan **numpy.float64** adalah beberapa contohnya.

**ndarray.itemsize** : ukuran dalam byte dari setiap elemen array. Sebagai contoh, sebuah array dari elemen tipe **float64** memiliki **itemsize** 8 (= 64/8), sedangkan satu dari tipe **complex32** memiliki **itemsize** 4 (= 32/8). Ini sama dengan **ndarray.dtype.itemsize**.

**ndarray.data** : buffer yang mengandung elemen sebenarnya dari array. Biasanya, kita tidak perlu menggunakan atribut ini karena kita akan mengakses elemen dalam array menggunakan fasilitas pengindeksan.

Contoh :

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

## Membuat Array

Ada beberapa cara untuk membuat array. Misalnya, Anda dapat membuat array dari list Python biasa atau pasangan menggunakan fungsi **array**. Tipe array yang dihasilkan disimpulkan dari tipe elemen dalam array.

In [11]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

Kesalahan yang sering terjadi dalam pembuatan **array** diantaranya adalah: 

In [ ]:
a = np.array(1,2,3,4) # WRONG 
a = np.array([1,2,3,4]) # RIGHT 

**array** mengubah barisan dari sebuah barisan menjadi **array** dua dimensi, barisan dari barisan sebuah barisan menjadi **array** tiga dimensi, dan seterusnya.


In [14]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Jenis **array** juga dapat secara eksplisit ditentukan pada saat pembuatan:


In [15]:
c = np.array([[1,2], [3,4]], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Seringkali, elemen dari sebuah **array** pada awalnya tidak diketahui, namun ukurannya diketahui. Oleh karena itu, NumPy menawarkan beberapa fungsi untuk membuat **array** yang memuat nilai awal. Hal tersebut dapat meminimalkan pertumbuhan memori yang diperlukan **array**, sebagai operasi yang dianggap mahal. 

Fungsi **zeros** menciptakan sebuah **array** yang berisi angka nol, fungsi **ones** yang menciptakan **array** yang berisi angka satu, dan fungsi **empty** menciptakan array yang isinya acak dan bergantung pada keadaan memori. Secara default, **dtype** dari **array** yang dibuat adalah **float64**.

In [16]:
# Fungsi zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# Fungsi ones
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
# Fungsi empty
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Untuk membuat barisan angka, NumPy menyediakan fungsi yang mirip dengan **range** yang outputnya berupa **array** dan bukan berupa list.


In [20]:
# barisan angka
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

Jika **arange** digunakan dengan argumen floating point,biasanya sulit memprediksi jumlah elemen yang diperoleh,karena presisi floating point yang terbatas. Untuk itu, lebih baik menggunakan fungsi linspace yang dapat menerima masukan berapa jumlah elemen yang kita inginkan:


In [22]:
# Fungsi linspace
from numpy import pi
np.linspace(0,2,9) # 9 angka dari 0 sampai 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
x = np.linspace(0,2*pi,100)

In [24]:
f = np.sin(x)

## Menampilkan Array

Saat kita menampilkan **array**, NumPy menampilkannya dengan cara yang mirip dengan daftar bersarang, namun dengan tata letak berikut:

• axis terakhir dicetak dari kiri ke kanan, 

• yang kedua sampai yang terakhir dicetak dari atas ke bawah, 

• Sisanya juga dicetak dari atas ke bawah,dengan masing-masing  potongan dipisahkan oleh sebuah baris kosong.


**array** satu dimensi dicetak sebagai baris, array dua dimensi sebagai matriks dan tridimensionals sebagai daftar matriks.


In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Jika **array** terlalu besar untuk ditampilkan, NumPy secara otomatis memotong bagian tengah **array** dan hanya mencetak ujung-ujungnya:


In [28]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [29]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Untuk memaksa NumPy mencetak seluruh bagian **array**, kita dapat mengubah opsi print menggunakan **set_printoptions**.


In [ ]:
np.set_printoptions(threshold=’nan’)